# Generated by Django 4.1.4 on 2023-01-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_cliente_dni_service_comprobante_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='factura',
            field=models.ImageField(blank=True, null=True, upload_to='factura'),
        ),
    ]
