# Generated by Django 4.1.4 on 2023-01-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0004_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='titulo',
            field=models.CharField(default='Titulo', max_length=15),
            preserve_default=False,
        ),
    ]
