# Generated by Django 4.1.4 on 2023-01-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0005_comentarios_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='fecha',
            field=models.DateField(default='2023-01-28'),
            preserve_default=False,
        ),
    ]
