# Generated by Django 4.1.4 on 2023-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0006_comentarios_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='autor',
            field=models.CharField(default='autor', max_length=100),
            preserve_default=False,
        ),
    ]
